// import Head from "next/head";
// import Image from "next/image";
// import { Inter } from "@next/font/google";
// import styles from "@/styles/Home.module.css";
// import ProductCarousel from "@/components/home/ourProduct/ProductCarousel";
// import Hero from "@/components/home/hero/Hero";
// import Outlet from "@/components/home/our-outlet/Outlet";
// import Banner from "@/components/home/banner/Banner";
// import CardGallery from "@/components/home/CardGallery/CardGallery";
// import HeaderHero from "@/components/home/HeaderHero";
// import { ToastContainer } from "react-toastify";

// const inter = Inter({ subsets: ["latin"] });
// export const getStaticProps = async () => {
//   const res = await fetch(
//     // "https://jsonplaceholder.typicode.com/posts"
//     "https://crabby-pocketbook-eel.cyclic.app/api/v1/product"
//   );
//   const data = await res.json();
//   return {
//     props: { data },
//     revalidate: 3,
//   };
// };
// export default function Home({ data }) {
//   return (
//     <>
//       <Head>
//         <title>Sultan Tea</title>
//         <meta name="description" content="Generated by Zoomit app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/main-logo.png" />
//       </Head>
//       <main className={styles.main}>
//         {/* follow this for folder structure */}
//         {/* https://github.com/leerob/leerob.io */}
//         <HeaderHero />
//         <Hero className="heroPosition" />
//         <ToastContainer
//           position="top-center"
//           autoClose={5000}
//           hideProgressBar={false}
//           newestOnTop={false}
//           closeOnClick
//           rtl={false}
//           pauseOnFocusLoss
//           draggable
//           pauseOnHover
//           theme="light"
//         />
//         <ProductCarousel data={data} />

//         <Banner />
//         <CardGallery />
//         <Outlet />
//       </main>
//     </>
//   );
// }




import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import OurbusinessShowcase from "@/components/our-brand/BusinessShowcase.js";
import Hero from "@/components/home/hero/Hero";
import Outlet from "@/components/home/our-outlet/Outlet";
import Banner from "@/components/home/banner/Banner";
import CardGallery from "@/components/home/CardGallery/CardGallery";
import HeaderHero from "@/components/home/HeaderHero";
import { ToastContainer } from "react-toastify";
import SultanTeaLogo from "/public/about-image-5.png";
import TeaLogo from "/public/logo-company.jpg";
import HeritageGP from "/public/heritage-gp.png";
const inter = Inter({ subsets: ["latin"] });

export const getStaticProps = async () => {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL;
  const apiUrl = `${baseUrl}/api/v1/brand`;
  console.log('Fetching data from:', apiUrl);

  try {
    const res = await fetch(apiUrl);

    if (!res.ok) {
      console.error('Failed to fetch data:', res.statusText);
      return {
        notFound: true,
      };
    }

    const brand = await res.json();
    return {
      props: { brand },
      revalidate: 3,
    };
  } catch (error) {
    console.error('Error fetching data:', error);
    return {
      props: { brand: [] }, // Return an empty array or handle the error as needed
      revalidate: 3,
    };
  }
};




export default function Home({ brand }) {
  return (
    <>
      <Head>
        <title>Sultan Tea</title>
        <meta name="description" content="Generated by Zoomit app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/main-logo.png" />
      </Head>
      <main className={styles.main}>
        <HeaderHero />
        <Hero className="heroPosition" />
        <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        {/* <ProductCarousel data={data} /> */}
        {/* <OurbusinessShowcase data={brand} /> */}

        <div className="container mb-2">
        <div className="d-flex  gap-5 justify-content-between align-items-center ">
           
          <div className="w-75 ">
            <Image src={HeritageGP} alt="Heritage GROUP" />
          </div>
          <div className="w-100 ">
            <Image src={TeaLogo} alt="ABOUT IMG" />
          </div>
          <div className="w-75">
            <Image src={SultanTeaLogo} alt="ABOUT IMG" />
          </div>
        </div>
      </div>
        <Banner />
        <CardGallery />
        <Outlet />
      </main>
    </>
  );
}
